/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class analisisNumerico */

#ifndef _Included_analisisNumerico
#define _Included_analisisNumerico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     analisisNumerico
 * Method:    puntoFijo
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_puntoFijo
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     analisisNumerico
 * Method:    biseccion
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_biseccion
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

/*
 * Class:     analisisNumerico
 * Method:    newtonRaphson
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_newtonRaphson
  (JNIEnv *, jobject, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
