/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class analisisNumerico */

#ifndef _Included_analisisNumerico
#define _Included_analisisNumerico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     analisisNumerico
 * Method:    puntoFijo
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_puntoFijo
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     analisisNumerico
 * Method:    biseccion
 * Signature: (DDDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_biseccion
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jstring);

/*
 * Class:     analisisNumerico
 * Method:    newtonRaphson
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDI)D
 */
JNIEXPORT jdouble JNICALL Java_analisisNumerico_newtonRaphson
  (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
